22/11/2022 16:52:32: error: uncaughtException: Illegal arguments: undefined, string
Error: Illegal arguments: undefined, string
    at Object.bcrypt.compareSync (/home/carlos/workspace/simple-tasks-api/simple-tasks-backend/node_modules/bcryptjs/dist/bcrypt.js:265:19)
    at /home/carlos/workspace/simple-tasks-api/simple-tasks-backend/src/services/loginService.ts:24:35
    at step (/home/carlos/workspace/simple-tasks-api/simple-tasks-backend/src/services/loginService.ts:33:23)
    at Object.next (/home/carlos/workspace/simple-tasks-api/simple-tasks-backend/src/services/loginService.ts:14:53)
    at /home/carlos/workspace/simple-tasks-api/simple-tasks-backend/src/services/loginService.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/carlos/workspace/simple-tasks-api/simple-tasks-backend/src/services/loginService.ts:4:12)
    at Query.<anonymous> (/home/carlos/workspace/simple-tasks-api/simple-tasks-backend/src/services/loginService.ts:15:88)
    at Query.handleReadyForQuery (/home/carlos/workspace/simple-tasks-api/simple-tasks-backend/node_modules/pg/lib/query.js:139:14)
    at Client._handleReadyForQuery (/home/carlos/workspace/simple-tasks-api/simple-tasks-backend/node_modules/pg/lib/client.js:290:19)
22/11/2022 16:53:33: error: uncaughtException: Illegal arguments: undefined, string
Error: Illegal arguments: undefined, string
    at Object.bcrypt.compareSync (/home/carlos/workspace/simple-tasks-api/simple-tasks-backend/node_modules/bcryptjs/dist/bcrypt.js:265:19)
    at /home/carlos/workspace/simple-tasks-api/simple-tasks-backend/src/services/loginService.ts:24:35
    at step (/home/carlos/workspace/simple-tasks-api/simple-tasks-backend/src/services/loginService.ts:33:23)
    at Object.next (/home/carlos/workspace/simple-tasks-api/simple-tasks-backend/src/services/loginService.ts:14:53)
    at /home/carlos/workspace/simple-tasks-api/simple-tasks-backend/src/services/loginService.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/carlos/workspace/simple-tasks-api/simple-tasks-backend/src/services/loginService.ts:4:12)
    at Query.<anonymous> (/home/carlos/workspace/simple-tasks-api/simple-tasks-backend/src/services/loginService.ts:15:88)
    at Query.handleReadyForQuery (/home/carlos/workspace/simple-tasks-api/simple-tasks-backend/node_modules/pg/lib/query.js:139:14)
    at Client._handleReadyForQuery (/home/carlos/workspace/simple-tasks-api/simple-tasks-backend/node_modules/pg/lib/client.js:290:19)
06/08/2023 19:11:06: error: uncaughtException: relation "migrations" does not exist
Error: relation "migrations" does not exist
    at /home/carlos/workspace/simple-tasks-backend/src/migrations/index.ts:51:17
    at step (/home/carlos/workspace/simple-tasks-backend/node_modules/tslib/tslib.js:141:27)
    at Object.next (/home/carlos/workspace/simple-tasks-backend/node_modules/tslib/tslib.js:122:57)
    at fulfilled (/home/carlos/workspace/simple-tasks-backend/node_modules/tslib/tslib.js:112:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
06/08/2023 19:14:57: error: uncaughtException: current transaction is aborted, commands ignored until end of transaction block
error: current transaction is aborted, commands ignored until end of transaction block
    at Parser.parseErrorMessage (/home/carlos/workspace/simple-tasks-backend/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/home/carlos/workspace/simple-tasks-backend/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/home/carlos/workspace/simple-tasks-backend/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/home/carlos/workspace/simple-tasks-backend/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
06/08/2023 19:15:31: error: uncaughtException: current transaction is aborted, commands ignored until end of transaction block
error: current transaction is aborted, commands ignored until end of transaction block
    at Parser.parseErrorMessage (/home/carlos/workspace/simple-tasks-backend/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/home/carlos/workspace/simple-tasks-backend/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/home/carlos/workspace/simple-tasks-backend/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/home/carlos/workspace/simple-tasks-backend/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
06/08/2023 19:16:19: error: uncaughtException: current transaction is aborted, commands ignored until end of transaction block
error: current transaction is aborted, commands ignored until end of transaction block
    at Parser.parseErrorMessage (/home/carlos/workspace/simple-tasks-backend/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/home/carlos/workspace/simple-tasks-backend/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/home/carlos/workspace/simple-tasks-backend/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/home/carlos/workspace/simple-tasks-backend/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
06/08/2023 19:17:28: error: uncaughtException: relation "migrations" does not exist
Error: relation "migrations" does not exist
    at /home/carlos/workspace/simple-tasks-backend/src/migrations/index.ts:145:13
    at step (/home/carlos/workspace/simple-tasks-backend/node_modules/tslib/tslib.js:141:27)
    at Object.next (/home/carlos/workspace/simple-tasks-backend/node_modules/tslib/tslib.js:122:57)
    at fulfilled (/home/carlos/workspace/simple-tasks-backend/node_modules/tslib/tslib.js:112:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
06/08/2023 19:18:50: error: uncaughtException: relation "migrations" does not exist
Error: relation "migrations" does not exist
    at /home/carlos/workspace/simple-tasks-backend/src/migrations/index.ts:143:13
    at step (/home/carlos/workspace/simple-tasks-backend/node_modules/tslib/tslib.js:141:27)
    at Object.next (/home/carlos/workspace/simple-tasks-backend/node_modules/tslib/tslib.js:122:57)
    at fulfilled (/home/carlos/workspace/simple-tasks-backend/node_modules/tslib/tslib.js:112:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
06/08/2023 19:20:44: error: uncaughtException: relation "migrations" does not exist
Error: relation "migrations" does not exist
    at /home/carlos/workspace/simple-tasks-backend/src/migrations/index.ts:144:13
    at step (/home/carlos/workspace/simple-tasks-backend/node_modules/tslib/tslib.js:141:27)
    at Object.next (/home/carlos/workspace/simple-tasks-backend/node_modules/tslib/tslib.js:122:57)
    at fulfilled (/home/carlos/workspace/simple-tasks-backend/node_modules/tslib/tslib.js:112:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
06/08/2023 19:22:37: error: uncaughtException: current transaction is aborted, commands ignored until end of transaction block
error: current transaction is aborted, commands ignored until end of transaction block
    at Parser.parseErrorMessage (/home/carlos/workspace/simple-tasks-backend/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/home/carlos/workspace/simple-tasks-backend/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/home/carlos/workspace/simple-tasks-backend/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/home/carlos/workspace/simple-tasks-backend/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
06/08/2023 19:23:36: error: uncaughtException: relation "migrations" does not exist
Error: relation "migrations" does not exist
    at /home/carlos/workspace/simple-tasks-backend/src/migrations/index.ts:144:13
    at step (/home/carlos/workspace/simple-tasks-backend/node_modules/tslib/tslib.js:141:27)
    at Object.next (/home/carlos/workspace/simple-tasks-backend/node_modules/tslib/tslib.js:122:57)
    at fulfilled (/home/carlos/workspace/simple-tasks-backend/node_modules/tslib/tslib.js:112:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
06/08/2023 19:25:27: error: uncaughtException: relation "migrations" does not exist
Error: relation "migrations" does not exist
    at /home/carlos/workspace/simple-tasks-backend/src/migrations/index.ts:148:13
    at step (/home/carlos/workspace/simple-tasks-backend/node_modules/tslib/tslib.js:141:27)
    at Object.next (/home/carlos/workspace/simple-tasks-backend/node_modules/tslib/tslib.js:122:57)
    at fulfilled (/home/carlos/workspace/simple-tasks-backend/node_modules/tslib/tslib.js:112:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
07/08/2023 13:22:06: error: uncaughtException: getaddrinfo ENOTFOUND postgres
Error: getaddrinfo ENOTFOUND postgres
    at /home/carlos/workspace/simple-tasks-backend/node_modules/pg-pool/index.js:45:11
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
07/08/2023 13:22:06: error: uncaughtException: getaddrinfo ENOTFOUND postgres
Error: getaddrinfo ENOTFOUND postgres
    at /home/carlos/workspace/simple-tasks-backend/node_modules/pg-pool/index.js:45:11
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
09/08/2023 20:02:42: error: uncaughtException: connect ECONNREFUSED 127.0.0.1:5432
Error: connect ECONNREFUSED 127.0.0.1:5432
    at /app/node_modules/pg-pool/index.js:45:11
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
09/08/2023 20:02:42: error: uncaughtException: connect ECONNREFUSED 127.0.0.1:5432
Error: connect ECONNREFUSED 127.0.0.1:5432
    at /app/node_modules/pg-pool/index.js:45:11
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
09/08/2023 20:03:50: error: uncaughtException: connect ECONNREFUSED 127.0.0.1:5432
Error: connect ECONNREFUSED 127.0.0.1:5432
    at /app/node_modules/pg-pool/index.js:45:11
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
09/08/2023 20:03:50: error: uncaughtException: connect ECONNREFUSED 127.0.0.1:5432
Error: connect ECONNREFUSED 127.0.0.1:5432
    at /app/node_modules/pg-pool/index.js:45:11
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
14/08/2023 12:10:01: error: uncaughtException: getaddrinfo EAI_AGAIN backend
Error: getaddrinfo EAI_AGAIN backend
    at /app/node_modules/pg-pool/index.js:45:11
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
14/08/2023 12:11:14: error: uncaughtException: no PostgreSQL user name specified in startup packet
error: no PostgreSQL user name specified in startup packet
    at /app/node_modules/pg-pool/index.js:45:11
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
14/08/2023 12:11:14: error: uncaughtException: no PostgreSQL user name specified in startup packet
error: no PostgreSQL user name specified in startup packet
    at /app/node_modules/pg-pool/index.js:45:11
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
14/08/2023 12:12:51: error: uncaughtException: no PostgreSQL user name specified in startup packet
error: no PostgreSQL user name specified in startup packet
    at /app/node_modules/pg-pool/index.js:45:11
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
14/08/2023 12:12:51: error: uncaughtException: no PostgreSQL user name specified in startup packet
error: no PostgreSQL user name specified in startup packet
    at /app/node_modules/pg-pool/index.js:45:11
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
23/08/2023 22:45:57: error: uncaughtException: terminating connection due to administrator command
error: terminating connection due to administrator command
    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/app/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/app/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/app/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:343:12)
    at readableAddChunk (node:internal/streams/readable:316:9)
    at Socket.Readable.push (node:internal/streams/readable:253:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
23/08/2023 22:45:57: error: uncaughtException: terminating connection due to administrator command
error: terminating connection due to administrator command
    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/app/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/app/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/app/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:343:12)
    at readableAddChunk (node:internal/streams/readable:316:9)
    at Socket.Readable.push (node:internal/streams/readable:253:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
23/08/2023 22:45:57: error: uncaughtException: terminating connection due to administrator command
error: terminating connection due to administrator command
    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/app/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/app/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/app/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:343:12)
    at readableAddChunk (node:internal/streams/readable:316:9)
    at Socket.Readable.push (node:internal/streams/readable:253:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
23/08/2023 22:45:57: error: uncaughtException: terminating connection due to administrator command
error: terminating connection due to administrator command
    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/app/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/app/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/app/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:343:12)
    at readableAddChunk (node:internal/streams/readable:316:9)
    at Socket.Readable.push (node:internal/streams/readable:253:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
